version: '3.8'

services:
  jupyter:
    container_name: ds-lab
    build:
      context: .
      dockerfile: Dockerfile
    image: ${HUB_URL}:ds-lab
    environment:
      - PYTHONPATH=/home/jovyan/projects
    entrypoint: ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root"]
    volumes:
      - ../jupiter-projects:/home/jovyan/projects
      - ${HOME}/.aws/credentials:/home/jovyan/.aws/credentials:ro
    ports:
    - 8888:8888
